site_name: 技術ノート
site_url: https://kf020501.github.io/tech-note/
repo_url: https://github.com/kf020501/tech-note

theme:
  name: material
  language: ja
  custom_dir: overrides   # overrides/main.html で noindex メタタグを挿入
  features:
    - navigation.sections
    - navigation.tabs
  font:
    code: Inconsolata
  logo: assets/memo_wh.png
  favicon: assets/memo_bl.png

extra_css:
  - assets/extra.css

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      noclasses: true
      pygments_style: borland
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kf020501
